### ISSUE TITLE
practica 1 ej 20

### ISSUE THREAD

**Issue by juanippo** [yagopajarino/uba-AyEd1#1]
En el 4, creo que no hace falta pedir que x sea mayor o igual a cero. Porque si es negativo, nunca vas a encontrar una raiz entera.
En el 6, tenés que pedir que z sea mayor a uno. Sino se te indefine con el 0. Y si lo dejás más grande que cero, te da verdadero siempre con el 1 porque el 1 divide a ambos.
En el 7 tambien tenes que pedir que z>1, por lo mismo.
En el 8,  por un lado me parece que despues de x mod z =0) deberias poner otro ) para encerrar el cuantificador. porque sino estás negando todas las preposiciones siguientes.
En el 9, es raro la manera en la que pedis que no sean primos consecutivos. Un caso particular de primos hermanos y que te da False, es el 23 y 29. Yo usé un cuantificador que vaya entre x e y y que pida que no exista primos en ese intervalo.

**Comment by yagopajarino** [comment]
En el 9 entendí que con lo de primos hermanos se refería a [primos gemelos](https://es.wikipedia.org/wiki/N%C3%BAmero_primo_gemelo) pero es verdad que pide que entre el x e y parámetros del pred devuelva True sii no hay otro primo en el medio.
El resto son correctos los cambios, ahora los modifico.

Cambio esos y en el 9 voy a armar los dos predicados para que queden los dos 😄

**Comment by yagopajarino** [comment]
Corregidos
