### ISSUE TITLE
P2.E2

### ISSUE THREAD

**Issue by juanippo** [yagopajarino/uba-AyEd1#2]
Hola! acá tenés mal el b),c) y h)

fijate que la primera posición de una seq es x[0] y el ultimo es x[|x|-1]. Y si vos haces subseq(x,d,h) toma los elementos de x[d] hasta x[h-1] inclusive, pero excluye x[h]

Entonces, el b) quedría Falso, porque el utlimo elemento de ese sebseq es x[|x|-2] y faltaría el x[|x|-1] 

El c) por el contrario queda verdadero porque el ultimo elemento es x[|x|-1] y el primero al ser x[0] coincide con la seq x.
El h) por lo mismo es verdadero.

**Comment by yagopajarino** [comment]
Graciass, ahí los revisé y coincido en las correcciones. Ahora lo modifico 👍

**Comment by yagopajarino** [comment]
Corregido, gracias!!
